name: Lands
main: me.angeschossen.lands.Lands
version: 3.7.2.1
author: Angeschossen
description: Feature rich GUI, Taxes, Customize your own, Titles, New factions - Let players manage their land!
website: https://www.spigotmc.org/resources/53313
api-version: 1.13

commands:
  lands:
    aliases: [land, l]
    description: Manage your land

permissions:
  lands.*:
    description: Access to all Lands actions
    default: op
    children:
      lands.chunks.<Number>:
        description: Set max chunk claims
        default: op
      lands.lands.<Number>:
        description: Set max lands can be member of (own lands + lands where member)
        default: op
      lands.ownlands.<Number>:
        description: Set max own lands (own lands)
        default: op
      lands.members.<Number>:
        description: Set max members in a land
        default: op
      lands.selection.<Selection>:
        description: Set max chunks in selection (/Lands selection)
        default: op
      lands.free.*:
        description: Player doesn't need to pay claim and land creation costs
        default: op
        children:
          lands.free.chunks.<Number>:
            description: Set free chunk claims
            default: op
          lands.free.lands.<Lands>:
            description: Set free land creations
            default: op
      lands.command.*:
        description: Access to all player commands
        children:
          lands.command.accept:
            description: /Lands accept
            default: op
          lands.command.chat:
            description: /Lands chat
            default: op
          lands.command.claim:
            description: /Lands claim
            default: op
          lands.command.create:
            description: /Lands create
            default: op
          lands.command.delete:
            description: /Lands delete
            default: op
          lands.command.deny:
            description: /Lands deny
            default: op
          lands.command.edit:
            description: /Lands edit
            default: op
          lands.command.help:
            description: /Lands help
            default: op
          lands.command.info:
            description: /Lands info
            default: op
          lands.command.invites:
            description: /Lands invites
            default: op
          lands.command.leave:
            description: /Lands leave
            default: op
          lands.command.menu:
            description: /Lands menu, /Lands
            default: op
          lands.command.rename:
            description: /Lands reload
            default: op
          lands.command.selection:
            description: /Lands selection
            default: op
          lands.command.setrole:
            description: /Lands setrole
            default: op
          lands.command.setspawn:
            description: /Lands setspawn
            default: op
          lands.command.spawn:
            description: /Lands spawn
            default: op
          lands.command.teleport:
            description: /Lands teleport
            default: op
          lands.command.top:
            description: /Lands top
            default: op
          lands.command.trust:
            description: /Lands trust
            default: op
          lands.command.unclaim:
            description: /Lands unclaim
            default: op
          lands.command.untrust:
            description: /Lands untrust
            default: op
          lands.command.view:
            description: /Lands view
            default: op
          lands.command.wild:
            description: /Lands wild
            default: op
      lands.bypass.*:
        description: Bypass all protections and other
        children:
          lands.bypass.break:
            description: Bypass block break protection
            default: op
          lands.bypass.place:
            description: Bypass block place protection
            default: op
          lands.bypass.interact:
            description: Bypass interaction protection
            default: op
          lands.bypass.combat.animal:
            description: Bypass animal attack protection
            default: op
          lands.bypass.combat.player:
            description: Bypass player attack protection
            default: op
          lands.bypass.member.untrust:
            description: Untrust players or remove invites in other lands
            default: op
          lands.bypass.fly:
            description: Bypass fly flag
            default: op
          lands.bypass.edit.*:
            description: Select lands you're not member of
            default: op
            children:
              lands.bypass.edit.settings:
                description: Edit settings of other lands
                default: op
          lands.bypass.cooldown.*:
            description: Bypass cooldowns
            default: op
            children:
              lands.bypass.cooldown.wild:
                description: Bypass /Lands wild cooldown
                default: op
              lands.bypass.cooldown.rename:
                description: Bypass /Lands rename cooldown
                default: op
              lands.bypass.cooldown.teleport:
                description: Bypass chunk teleport cooldown
                default: op
              lands.bypass.cooldown.spawn:
                description: Bypass /Lands spawn cooldown
                default: op
          lands.bypass.spawn.private:
            description: Teleport to private land spawns
            default: op
          lands.bypass.disallowwilderness.break:
            description: Allow block breaking in wilderness, if disallowwilderness is enabled
            default: op
          lands.bypass.disallowwilderness.place:
            description: Allow block place in wilderness, if disallowilderness is enabled
            default: op
          lands.bypass.disallowwilderness.interact:
            description: Allow interaction in wilderness, if disallowwilderness is enabled
      lands.gui.*:
        description: Access to all GUI actions
        default: op
        children:
          lands.gui.chunk.*:
            description: Access to all chunk GUI actions
            default: op
            children:
              lands.gui.chunk.teleport:
                description: Allow teleporting to claimed chunks
                default: op
      lands.setting.*:
        description: Access to land settings
        default: op
        children:
          lands.setting.entity_griefing:
            description: Allow to toggle entity griefing
            default: op
          lands.setting.piston_griefing:
            description: Allow to toggle piston griefing
            default: op
          lands.setting.monster_spawn:
            description: Allow to toggle monster spawn
            default: op
          lands.setting.animal_spawn:
            description: Allow to toggle animal spawn
            default: op
          lands.setting.tax_total:
            description: Allow toggle tax total
            default: op
          lands.setting.spawn_public:
            description: Allow to toggle land spawn public
            default: op
      lands.role.*:
        description: Access to all role settings
        default: op
        children:
          lands.role.visitor.*:
            description: Access to all visitor role settings
            default: op
            children:
              lands.role.visitor.block_break:
                description: Allow to toggle block break
                default: op
              lands.role.visitor.block_place:
                description: Allow to toggle block place
                default: op
              lands.role.visitor.attack_player:
                description: Allow to toggle attack player
                default: op
              lands.role.visitor.attack_animal:
                description: Allow to toggle attack animal
                default: op
              lands.role.visitor.block_ignite:
                description: Allow to toggle block ignite
                default: op
              lands.role.visitor.interact_general:
                description: Allow to toggle general interaction
                default: op
              lands.role.visitor.interact_doors:
                description: Allow to toggle open doors
                default: op
              lands.role.visitor.interact_container:
                description: Allow to toggle open container
                default: op
              lands.role.visitor.interact_mechanism:
                description: Allow to toggle interact mechanism (redstone)
                default: op
              lands.role.visitor.player_trust:
                description: Allow to toggle trust player
                default: op
              lands.role.visitor.player_untrust:
                description: Allow to toggle player untrust
                default: op
              lands.role.visitor.player_setrole:
                description: Allow to toggle player setrole
                default: op
              lands.role.visitor.land_claim:
                description: Allow to toggle claim chunks for the land
                default: op
              lands.role.visitor.land_claim_border:
                description: Allow to toggle claim chunks at the border of the land
                default: op
              lands.role.visitor.land_spawn_set:
                description: Allow to toggle spawn set
                default: op
              lands.role.visitor.land_spawn_teleport:
                description: Allow to toggle spawn teleport
                default: op
              lands.role.visitor.land_rename:
                description: Allow to rename land
                default: op
              lands.role.visitor.setting_edit:
                description: Allow to toggle alow this role to change settings of a role with lower priority
                default: op
          lands.role.member.*:
            description: Access to all mmeber role settings
            default: op
            children:
              lands.role.member.block_break:
                description: Allow to toggle block break
                default: op
              lands.role.member.block_place:
                description: Allow to toggle block place
                default: op
              lands.role.member.attack_player:
                description: Allow to toggle attack player
                default: op
              lands.role.member.attack_animal:
                description: Allow to toggle attack animal
                default: op
              lands.role.member.block_ignite:
                description: Allow to toggle block ignite
                default: op
              lands.role.member.interact_general:
                description: Allow to toggle general interaction
                default: op
              lands.role.member.interact_doors:
                description: Allow to toggle open doors
                default: op
              lands.role.member.interact_container:
                description: Allow to toggle open container
                default: op
              lands.role.member.interact_mechanism:
                description: Allow to toggle interact mechanism (redstone)
                default: op
              lands.role.member.player_trust:
                description: Allow to toggle trust player
                default: op
              lands.role.member.player_untrust:
                description: Allow to toggle player untrust
                default: op
              lands.role.member.player_setrole:
                description: Allow to toggle player setrole
                default: op
              lands.role.member.land_claim:
                description: Allow to toggle claim chunks for the land
                default: op
              lands.role.member.land_claim_border:
                description: Allow to toggle claim chunks at the border of the land
                default: op
              lands.role.member.land_spawn_set:
                description: Allow to toggle spawn set
                default: op
              lands.role.member.land_spawn_teleport:
                description: Allow to toggle spawn teleport
                default: op
              lands.role.member.land_rename:
                description: Allow to rename land
                default: op
              lands.role.member.setting_edit:
                description: Allow to toggle alow this role to change settings of a role with lower priority
                default: op
          lands.role.admin.*:
            description: Access to all admin role settings
            default: op
            children:
              lands.role.admin.block_break:
                description: Allow to toggle block break
                default: op
              lands.role.admin.block_place:
                description: Allow to toggle block place
                default: op
              lands.role.admin.attack_player:
                description: Allow to toggle attack player
                default: op
              lands.role.admin.attack_animal:
                description: Allow to toggle attack animal
                default: op
              lands.role.admin.block_ignite:
                description: Allow to toggle block ignite
                default: op
              lands.role.admin.interact_general:
                description: Allow to toggle general interaction
                default: op
              lands.role.admin.interact_doors:
                description: Allow to toggle open doors
                default: op
              lands.role.admin.interact_container:
                description: Allow to toggle open container
                default: op
              lands.role.admin.interact_mechanism:
                description: Allow to toggle interact mechanism (redstone)
                default: op
              lands.role.admin.player_trust:
                description: Allow to toggle trust player
                default: op
              lands.role.admin.player_untrust:
                description: Allow to toggle player untrust
                default: op
              lands.role.admin.player_setrole:
                description: Allow to toggle player setrole
                default: op
              lands.role.admin.land_claim:
                description: Allow to toggle claim chunks for the land
                default: op
              lands.role.admin.land_claim_border:
                description: Allow to toggle claim chunks at the border of the land
                default: op
              lands.role.admin.land_spawn_set:
                description: Allow to toggle spawn set
                default: op
              lands.role.admin.land_spawn_teleport:
                description: Allow to toggle spawn teleport
                default: op
              lands.role.admin.land_rename:
                description: Allow to rename land
                default: op
              lands.role.admin.setting_edit:
                description: Allow to toggle alow this role to change settings of a role with lower priority
                default: op
      lands.admin.*:
        description: Access to all admin actions
        default: op
        children:
          lands.admin.command.*:
            description: Access to all admin commands
            default: op
            children:
              lands.admin.command.reload:
                description: Access to /Lands reload
                default: op
              lands.admin.command.land.*:
                description: Access to admin land commands
                default: op
                children:
                  lands.admin.command.land.delete:
                    description: Delete land
                    default: op
                  lands.admin.command.land.edit:
                    description: Open GUI for land
                    default: op
                  lands.admin.command.land.trust:
                    description: Trust players to land
                    default: op
                  lands.admin.command.land.untrust:
                    description: Untrust players from land
                    default: op
                  lands.admin.command.land.rename:
                    description: Rename land
                    default: op
                  lands.admin.command.land.settings.reset:
                    description: Reset settings of land
                    default: op
                  lands.admin.command.land.setowner:
                    description: Set new owner for land
                    default: op
              lands.admin.command.give.claimblock:
                description: Give claimblocks to player
                default: op
              lands.admin.command.import:
                description: Import data from other plugins
                default: op
              lands.admin.command.safezone:
                description: Edit safezones
                default: op

